// flow-typed signature: b3fd70e48ae114166d834348d402884d
// flow-typed version: <<STUB>>/google-closure-compiler-js_v^20171203.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'google-closure-compiler-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'google-closure-compiler-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'google-closure-compiler-js/build_compiler' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/cmd' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/compile' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/ace-1.2.3' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular_ui_router' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.0' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.2-http-promise_templated' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.2-http-promise' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.2-q_templated' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.2-q' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.2' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.3-http-promise_templated' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.3-http-promise' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.3-mocks' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.3-q_templated' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.3-q' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.3-resource' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.3' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.4-http-promise_templated' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.4-mocks' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.4-q_templated' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.4-resource' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.4-test' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.4' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.5-http-promise_templated' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.5-mocks' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.5-q_templated' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.5-resource' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.5-test' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.5' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.6-function-properties' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.6-http-promise_templated' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.6-mocks' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.6-q_templated' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.6-resource' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.6-test' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-1.6' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-cache-2.3.0' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-cache-4.6' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-material-1.1' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/angular-material' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/google.container' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/iframes' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/oauth' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/oauth2' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/opensocial' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/plusone' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/shindig' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/async-2.0' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/chai-3.5' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/chrome_extensions' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/chrome' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/empty' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/facebook_javascript_sdk' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/fileapi_synchronous' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/google_analytics_api' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/google_feed_api' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/google_loader_api' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/google_tag_manager_api' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/google_universal_analytics_api' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/google_visualization_api' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/google_youtube_iframe' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jasmine-2.0' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jasmine-angular' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jasmine' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jquery-1.12_and_2.2' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jquery-1.4.4' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jquery-1.5' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jquery-1.6' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jquery-1.7' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jquery-1.8' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jquery-1.9' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jquery-3.0' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jquery-3.1' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/jquery-3.2' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_10' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_11' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_12' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_13' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_14' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_15' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_16' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_17' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_18' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_19' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_20' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_21' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_22' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_23' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_24' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_25' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_26' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_27' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_28' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_29' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_3' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_4' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_5' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_6' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_7' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_8' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_9' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_exp' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/mocha-2.5' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/polymer-1.0' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/processing-1.4.8' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/safari' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/showdown-1.3' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/silverlight' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/sinon-1.17' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/sinon-chai-2.7' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/stripe-2.0' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/svg' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/typeahead_jquery_0_11_1' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/ui-bootstrap' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/underscore-1.3.1' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/underscore-1.4.4' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/underscore-1.5.2' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/universal_analytics_api' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/w3c_clipboardevent' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/w3c_eventsource' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/web_component_tester-4.2' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/webassembly' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/externs/youtubeplayer' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/assert' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/buffer' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/child_process' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/cluster' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/crypto' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/dgram' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/dns' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/domain' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/events' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/fs' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/globals' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/http' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/https' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/net' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/os' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/path' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/punycode' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/querystring' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/readline' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/repl' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/stream' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/string_decoder' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/tls' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/tty' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/url' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/util' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/vm' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/contrib/nodejs/zlib' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/jscomp' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/lib/gulp' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/lib/webpack' {
  declare module.exports: any;
}

declare module 'google-closure-compiler-js/logger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'google-closure-compiler-js/build_compiler.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/build_compiler'>;
}
declare module 'google-closure-compiler-js/cmd.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/cmd'>;
}
declare module 'google-closure-compiler-js/compile.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/compile'>;
}
declare module 'google-closure-compiler-js/contrib/externs/ace-1.2.3.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/ace-1.2.3'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular_ui_router.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular_ui_router'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.0.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.0'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.2-http-promise_templated.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.2-http-promise_templated'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.2-http-promise.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.2-http-promise'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.2-q_templated.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.2-q_templated'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.2-q.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.2-q'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.2.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.2'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.3-http-promise_templated.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.3-http-promise_templated'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.3-http-promise.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.3-http-promise'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.3-mocks.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.3-mocks'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.3-q_templated.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.3-q_templated'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.3-q.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.3-q'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.3-resource.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.3-resource'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.3.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.3'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.4-http-promise_templated.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.4-http-promise_templated'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.4-mocks.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.4-mocks'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.4-q_templated.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.4-q_templated'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.4-resource.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.4-resource'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.4-test.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.4-test'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.4.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.4'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.5-http-promise_templated.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.5-http-promise_templated'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.5-mocks.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.5-mocks'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.5-q_templated.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.5-q_templated'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.5-resource.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.5-resource'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.5-test.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.5-test'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.5.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.5'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.6-function-properties.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.6-function-properties'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.6-http-promise_templated.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.6-http-promise_templated'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.6-mocks.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.6-mocks'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.6-q_templated.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.6-q_templated'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.6-resource.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.6-resource'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.6-test.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.6-test'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-1.6.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-1.6'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-cache-2.3.0.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-cache-2.3.0'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-cache-4.6.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-cache-4.6'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-material-1.1.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-material-1.1'>;
}
declare module 'google-closure-compiler-js/contrib/externs/angular-material.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/angular-material'>;
}
declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/google.container.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/api/gadgets/google.container'>;
}
declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/iframes.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/api/gadgets/iframes'>;
}
declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/oauth.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/api/gadgets/oauth'>;
}
declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/oauth2.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/api/gadgets/oauth2'>;
}
declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/opensocial.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/api/gadgets/opensocial'>;
}
declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/plusone.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/api/gadgets/plusone'>;
}
declare module 'google-closure-compiler-js/contrib/externs/api/gadgets/shindig.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/api/gadgets/shindig'>;
}
declare module 'google-closure-compiler-js/contrib/externs/async-2.0.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/async-2.0'>;
}
declare module 'google-closure-compiler-js/contrib/externs/chai-3.5.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/chai-3.5'>;
}
declare module 'google-closure-compiler-js/contrib/externs/chrome_extensions.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/chrome_extensions'>;
}
declare module 'google-closure-compiler-js/contrib/externs/chrome.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/chrome'>;
}
declare module 'google-closure-compiler-js/contrib/externs/empty.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/empty'>;
}
declare module 'google-closure-compiler-js/contrib/externs/facebook_javascript_sdk.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/facebook_javascript_sdk'>;
}
declare module 'google-closure-compiler-js/contrib/externs/fileapi_synchronous.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/fileapi_synchronous'>;
}
declare module 'google-closure-compiler-js/contrib/externs/google_analytics_api.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/google_analytics_api'>;
}
declare module 'google-closure-compiler-js/contrib/externs/google_feed_api.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/google_feed_api'>;
}
declare module 'google-closure-compiler-js/contrib/externs/google_loader_api.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/google_loader_api'>;
}
declare module 'google-closure-compiler-js/contrib/externs/google_tag_manager_api.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/google_tag_manager_api'>;
}
declare module 'google-closure-compiler-js/contrib/externs/google_universal_analytics_api.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/google_universal_analytics_api'>;
}
declare module 'google-closure-compiler-js/contrib/externs/google_visualization_api.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/google_visualization_api'>;
}
declare module 'google-closure-compiler-js/contrib/externs/google_youtube_iframe.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/google_youtube_iframe'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jasmine-2.0.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jasmine-2.0'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jasmine-angular.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jasmine-angular'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jasmine.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jasmine'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jquery-1.12_and_2.2.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jquery-1.12_and_2.2'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jquery-1.4.4.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jquery-1.4.4'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jquery-1.5.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jquery-1.5'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jquery-1.6.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jquery-1.6'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jquery-1.7.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jquery-1.7'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jquery-1.8.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jquery-1.8'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jquery-1.9.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jquery-1.9'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jquery-3.0.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jquery-3.0'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jquery-3.1.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jquery-3.1'>;
}
declare module 'google-closure-compiler-js/contrib/externs/jquery-3.2.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/jquery-3.2'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_10.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_10'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_11.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_11'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_12.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_12'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_13.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_13'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_14.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_14'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_15.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_15'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_16.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_16'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_17.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_17'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_18.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_18'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_19.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_19'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_20.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_20'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_21.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_21'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_22.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_22'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_23.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_23'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_24.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_24'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_25.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_25'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_26.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_26'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_27.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_27'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_28.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_28'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_29.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_29'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_3.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_3'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_4.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_4'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_5.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_5'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_6.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_6'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_7.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_7'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_8.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_8'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_9.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_9'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_exp.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3_exp'>;
}
declare module 'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/maps/google_maps_api_v3'>;
}
declare module 'google-closure-compiler-js/contrib/externs/mocha-2.5.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/mocha-2.5'>;
}
declare module 'google-closure-compiler-js/contrib/externs/polymer-1.0.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/polymer-1.0'>;
}
declare module 'google-closure-compiler-js/contrib/externs/processing-1.4.8.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/processing-1.4.8'>;
}
declare module 'google-closure-compiler-js/contrib/externs/safari.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/safari'>;
}
declare module 'google-closure-compiler-js/contrib/externs/showdown-1.3.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/showdown-1.3'>;
}
declare module 'google-closure-compiler-js/contrib/externs/silverlight.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/silverlight'>;
}
declare module 'google-closure-compiler-js/contrib/externs/sinon-1.17.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/sinon-1.17'>;
}
declare module 'google-closure-compiler-js/contrib/externs/sinon-chai-2.7.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/sinon-chai-2.7'>;
}
declare module 'google-closure-compiler-js/contrib/externs/stripe-2.0.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/stripe-2.0'>;
}
declare module 'google-closure-compiler-js/contrib/externs/svg.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/svg'>;
}
declare module 'google-closure-compiler-js/contrib/externs/typeahead_jquery_0_11_1.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/typeahead_jquery_0_11_1'>;
}
declare module 'google-closure-compiler-js/contrib/externs/ui-bootstrap.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/ui-bootstrap'>;
}
declare module 'google-closure-compiler-js/contrib/externs/underscore-1.3.1.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/underscore-1.3.1'>;
}
declare module 'google-closure-compiler-js/contrib/externs/underscore-1.4.4.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/underscore-1.4.4'>;
}
declare module 'google-closure-compiler-js/contrib/externs/underscore-1.5.2.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/underscore-1.5.2'>;
}
declare module 'google-closure-compiler-js/contrib/externs/universal_analytics_api.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/universal_analytics_api'>;
}
declare module 'google-closure-compiler-js/contrib/externs/w3c_clipboardevent.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/w3c_clipboardevent'>;
}
declare module 'google-closure-compiler-js/contrib/externs/w3c_eventsource.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/w3c_eventsource'>;
}
declare module 'google-closure-compiler-js/contrib/externs/web_component_tester-4.2.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/web_component_tester-4.2'>;
}
declare module 'google-closure-compiler-js/contrib/externs/webassembly.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/webassembly'>;
}
declare module 'google-closure-compiler-js/contrib/externs/youtubeplayer.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/externs/youtubeplayer'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/assert.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/assert'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/buffer.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/buffer'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/child_process.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/child_process'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/cluster.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/cluster'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/crypto.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/crypto'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/dgram.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/dgram'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/dns.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/dns'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/domain.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/domain'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/events.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/events'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/fs.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/fs'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/globals.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/globals'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/http.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/http'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/https.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/https'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/net.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/net'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/os.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/os'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/path.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/path'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/punycode.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/punycode'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/querystring.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/querystring'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/readline.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/readline'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/repl.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/repl'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/stream.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/stream'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/string_decoder.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/string_decoder'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/tls.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/tls'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/tty.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/tty'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/url.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/url'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/util.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/util'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/vm.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/vm'>;
}
declare module 'google-closure-compiler-js/contrib/nodejs/zlib.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/contrib/nodejs/zlib'>;
}
declare module 'google-closure-compiler-js/index' {
  declare module.exports: $Exports<'google-closure-compiler-js'>;
}
declare module 'google-closure-compiler-js/index.js' {
  declare module.exports: $Exports<'google-closure-compiler-js'>;
}
declare module 'google-closure-compiler-js/jscomp.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/jscomp'>;
}
declare module 'google-closure-compiler-js/lib/gulp.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/lib/gulp'>;
}
declare module 'google-closure-compiler-js/lib/webpack.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/lib/webpack'>;
}
declare module 'google-closure-compiler-js/logger.js' {
  declare module.exports: $Exports<'google-closure-compiler-js/logger'>;
}
