// flow-typed signature: f604d64d2fa4b4af3811b9c488ea9e9f
// flow-typed version: <<STUB>>/javascript-state-machine_v^3.0.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'javascript-state-machine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'javascript-state-machine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'javascript-state-machine/dist/state-machine-history' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/dist/state-machine-history.min' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/dist/state-machine-visualize' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/dist/state-machine-visualize.min' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/dist/state-machine' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/dist/state-machine.min' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/lib/history' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/lib/state-machine' {
  declare module.exports: any;
}

declare module 'javascript-state-machine/lib/visualize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'javascript-state-machine/dist/state-machine-history.js' {
  declare module.exports: $Exports<'javascript-state-machine/dist/state-machine-history'>;
}
declare module 'javascript-state-machine/dist/state-machine-history.min.js' {
  declare module.exports: $Exports<'javascript-state-machine/dist/state-machine-history.min'>;
}
declare module 'javascript-state-machine/dist/state-machine-visualize.js' {
  declare module.exports: $Exports<'javascript-state-machine/dist/state-machine-visualize'>;
}
declare module 'javascript-state-machine/dist/state-machine-visualize.min.js' {
  declare module.exports: $Exports<'javascript-state-machine/dist/state-machine-visualize.min'>;
}
declare module 'javascript-state-machine/dist/state-machine.js' {
  declare module.exports: $Exports<'javascript-state-machine/dist/state-machine'>;
}
declare module 'javascript-state-machine/dist/state-machine.min.js' {
  declare module.exports: $Exports<'javascript-state-machine/dist/state-machine.min'>;
}
declare module 'javascript-state-machine/lib/history.js' {
  declare module.exports: $Exports<'javascript-state-machine/lib/history'>;
}
declare module 'javascript-state-machine/lib/state-machine.js' {
  declare module.exports: $Exports<'javascript-state-machine/lib/state-machine'>;
}
declare module 'javascript-state-machine/lib/visualize.js' {
  declare module.exports: $Exports<'javascript-state-machine/lib/visualize'>;
}
