// flow-typed signature: cd69cbdb5166a5f1630c64fbe277a24a
// flow-typed version: <<STUB>>/planck-js_v^0.1.38/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'planck-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'planck-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'planck-js/dist/planck-with-testbed' {
  declare module.exports: any;
}

declare module 'planck-js/dist/planck-with-testbed.min' {
  declare module.exports: any;
}

declare module 'planck-js/dist/planck' {
  declare module.exports: any;
}

declare module 'planck-js/dist/planck.min' {
  declare module.exports: any;
}

declare module 'planck-js/lib/Body' {
  declare module.exports: any;
}

declare module 'planck-js/lib/collision/AABB' {
  declare module.exports: any;
}

declare module 'planck-js/lib/collision/BroadPhase' {
  declare module.exports: any;
}

declare module 'planck-js/lib/collision/Distance' {
  declare module.exports: any;
}

declare module 'planck-js/lib/collision/DynamicTree' {
  declare module.exports: any;
}

declare module 'planck-js/lib/collision/TimeOfImpact' {
  declare module.exports: any;
}

declare module 'planck-js/lib/common/Jacobian' {
  declare module.exports: any;
}

declare module 'planck-js/lib/common/Mat22' {
  declare module.exports: any;
}

declare module 'planck-js/lib/common/Mat33' {
  declare module.exports: any;
}

declare module 'planck-js/lib/common/Math' {
  declare module.exports: any;
}

declare module 'planck-js/lib/common/Position' {
  declare module.exports: any;
}

declare module 'planck-js/lib/common/Rot' {
  declare module.exports: any;
}

declare module 'planck-js/lib/common/stats' {
  declare module.exports: any;
}

declare module 'planck-js/lib/common/Sweep' {
  declare module.exports: any;
}

declare module 'planck-js/lib/common/Transform' {
  declare module.exports: any;
}

declare module 'planck-js/lib/common/Vec2' {
  declare module.exports: any;
}

declare module 'planck-js/lib/common/Vec3' {
  declare module.exports: any;
}

declare module 'planck-js/lib/common/Velocity' {
  declare module.exports: any;
}

declare module 'planck-js/lib/Contact' {
  declare module.exports: any;
}

declare module 'planck-js/lib/Fixture' {
  declare module.exports: any;
}

declare module 'planck-js/lib/index' {
  declare module.exports: any;
}

declare module 'planck-js/lib/Joint' {
  declare module.exports: any;
}

declare module 'planck-js/lib/joint/DistanceJoint' {
  declare module.exports: any;
}

declare module 'planck-js/lib/joint/FrictionJoint' {
  declare module.exports: any;
}

declare module 'planck-js/lib/joint/GearJoint' {
  declare module.exports: any;
}

declare module 'planck-js/lib/joint/MotorJoint' {
  declare module.exports: any;
}

declare module 'planck-js/lib/joint/MouseJoint' {
  declare module.exports: any;
}

declare module 'planck-js/lib/joint/PrismaticJoint' {
  declare module.exports: any;
}

declare module 'planck-js/lib/joint/PulleyJoint' {
  declare module.exports: any;
}

declare module 'planck-js/lib/joint/RevoluteJoint' {
  declare module.exports: any;
}

declare module 'planck-js/lib/joint/RopeJoint' {
  declare module.exports: any;
}

declare module 'planck-js/lib/joint/WeldJoint' {
  declare module.exports: any;
}

declare module 'planck-js/lib/joint/WheelJoint' {
  declare module.exports: any;
}

declare module 'planck-js/lib/license' {
  declare module.exports: any;
}

declare module 'planck-js/lib/Manifold' {
  declare module.exports: any;
}

declare module 'planck-js/lib/Rope' {
  declare module.exports: any;
}

declare module 'planck-js/lib/Settings' {
  declare module.exports: any;
}

declare module 'planck-js/lib/Shape' {
  declare module.exports: any;
}

declare module 'planck-js/lib/shape/BoxShape' {
  declare module.exports: any;
}

declare module 'planck-js/lib/shape/ChainShape' {
  declare module.exports: any;
}

declare module 'planck-js/lib/shape/CircleShape' {
  declare module.exports: any;
}

declare module 'planck-js/lib/shape/CollideCircle' {
  declare module.exports: any;
}

declare module 'planck-js/lib/shape/CollideCirclePolygone' {
  declare module.exports: any;
}

declare module 'planck-js/lib/shape/CollideEdgeCircle' {
  declare module.exports: any;
}

declare module 'planck-js/lib/shape/CollideEdgePolygon' {
  declare module.exports: any;
}

declare module 'planck-js/lib/shape/CollidePolygon' {
  declare module.exports: any;
}

declare module 'planck-js/lib/shape/EdgeShape' {
  declare module.exports: any;
}

declare module 'planck-js/lib/shape/PolygonShape' {
  declare module.exports: any;
}

declare module 'planck-js/lib/Solver' {
  declare module.exports: any;
}

declare module 'planck-js/lib/util/common' {
  declare module.exports: any;
}

declare module 'planck-js/lib/util/create' {
  declare module.exports: any;
}

declare module 'planck-js/lib/util/options' {
  declare module.exports: any;
}

declare module 'planck-js/lib/util/Pool' {
  declare module.exports: any;
}

declare module 'planck-js/lib/util/Timer' {
  declare module.exports: any;
}

declare module 'planck-js/lib/World' {
  declare module.exports: any;
}

declare module 'planck-js/test/BasicTest' {
  declare module.exports: any;
}

declare module 'planck-js/test/CCDTest' {
  declare module.exports: any;
}

declare module 'planck-js/test/CollisionTest' {
  declare module.exports: any;
}

declare module 'planck-js/test/MathTest' {
  declare module.exports: any;
}

declare module 'planck-js/test/PoolTest' {
  declare module.exports: any;
}

declare module 'planck-js/test/testutil/expect' {
  declare module.exports: any;
}

declare module 'planck-js/test/testutil/memo' {
  declare module.exports: any;
}

declare module 'planck-js/testbed/client' {
  declare module.exports: any;
}

declare module 'planck-js/testbed/index' {
  declare module.exports: any;
}

declare module 'planck-js/testbed/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'planck-js/dist/planck-with-testbed.js' {
  declare module.exports: $Exports<'planck-js/dist/planck-with-testbed'>;
}
declare module 'planck-js/dist/planck-with-testbed.min.js' {
  declare module.exports: $Exports<'planck-js/dist/planck-with-testbed.min'>;
}
declare module 'planck-js/dist/planck.js' {
  declare module.exports: $Exports<'planck-js/dist/planck'>;
}
declare module 'planck-js/dist/planck.min.js' {
  declare module.exports: $Exports<'planck-js/dist/planck.min'>;
}
declare module 'planck-js/lib/Body.js' {
  declare module.exports: $Exports<'planck-js/lib/Body'>;
}
declare module 'planck-js/lib/collision/AABB.js' {
  declare module.exports: $Exports<'planck-js/lib/collision/AABB'>;
}
declare module 'planck-js/lib/collision/BroadPhase.js' {
  declare module.exports: $Exports<'planck-js/lib/collision/BroadPhase'>;
}
declare module 'planck-js/lib/collision/Distance.js' {
  declare module.exports: $Exports<'planck-js/lib/collision/Distance'>;
}
declare module 'planck-js/lib/collision/DynamicTree.js' {
  declare module.exports: $Exports<'planck-js/lib/collision/DynamicTree'>;
}
declare module 'planck-js/lib/collision/TimeOfImpact.js' {
  declare module.exports: $Exports<'planck-js/lib/collision/TimeOfImpact'>;
}
declare module 'planck-js/lib/common/Jacobian.js' {
  declare module.exports: $Exports<'planck-js/lib/common/Jacobian'>;
}
declare module 'planck-js/lib/common/Mat22.js' {
  declare module.exports: $Exports<'planck-js/lib/common/Mat22'>;
}
declare module 'planck-js/lib/common/Mat33.js' {
  declare module.exports: $Exports<'planck-js/lib/common/Mat33'>;
}
declare module 'planck-js/lib/common/Math.js' {
  declare module.exports: $Exports<'planck-js/lib/common/Math'>;
}
declare module 'planck-js/lib/common/Position.js' {
  declare module.exports: $Exports<'planck-js/lib/common/Position'>;
}
declare module 'planck-js/lib/common/Rot.js' {
  declare module.exports: $Exports<'planck-js/lib/common/Rot'>;
}
declare module 'planck-js/lib/common/stats.js' {
  declare module.exports: $Exports<'planck-js/lib/common/stats'>;
}
declare module 'planck-js/lib/common/Sweep.js' {
  declare module.exports: $Exports<'planck-js/lib/common/Sweep'>;
}
declare module 'planck-js/lib/common/Transform.js' {
  declare module.exports: $Exports<'planck-js/lib/common/Transform'>;
}
declare module 'planck-js/lib/common/Vec2.js' {
  declare module.exports: $Exports<'planck-js/lib/common/Vec2'>;
}
declare module 'planck-js/lib/common/Vec3.js' {
  declare module.exports: $Exports<'planck-js/lib/common/Vec3'>;
}
declare module 'planck-js/lib/common/Velocity.js' {
  declare module.exports: $Exports<'planck-js/lib/common/Velocity'>;
}
declare module 'planck-js/lib/Contact.js' {
  declare module.exports: $Exports<'planck-js/lib/Contact'>;
}
declare module 'planck-js/lib/Fixture.js' {
  declare module.exports: $Exports<'planck-js/lib/Fixture'>;
}
declare module 'planck-js/lib/index.js' {
  declare module.exports: $Exports<'planck-js/lib/index'>;
}
declare module 'planck-js/lib/Joint.js' {
  declare module.exports: $Exports<'planck-js/lib/Joint'>;
}
declare module 'planck-js/lib/joint/DistanceJoint.js' {
  declare module.exports: $Exports<'planck-js/lib/joint/DistanceJoint'>;
}
declare module 'planck-js/lib/joint/FrictionJoint.js' {
  declare module.exports: $Exports<'planck-js/lib/joint/FrictionJoint'>;
}
declare module 'planck-js/lib/joint/GearJoint.js' {
  declare module.exports: $Exports<'planck-js/lib/joint/GearJoint'>;
}
declare module 'planck-js/lib/joint/MotorJoint.js' {
  declare module.exports: $Exports<'planck-js/lib/joint/MotorJoint'>;
}
declare module 'planck-js/lib/joint/MouseJoint.js' {
  declare module.exports: $Exports<'planck-js/lib/joint/MouseJoint'>;
}
declare module 'planck-js/lib/joint/PrismaticJoint.js' {
  declare module.exports: $Exports<'planck-js/lib/joint/PrismaticJoint'>;
}
declare module 'planck-js/lib/joint/PulleyJoint.js' {
  declare module.exports: $Exports<'planck-js/lib/joint/PulleyJoint'>;
}
declare module 'planck-js/lib/joint/RevoluteJoint.js' {
  declare module.exports: $Exports<'planck-js/lib/joint/RevoluteJoint'>;
}
declare module 'planck-js/lib/joint/RopeJoint.js' {
  declare module.exports: $Exports<'planck-js/lib/joint/RopeJoint'>;
}
declare module 'planck-js/lib/joint/WeldJoint.js' {
  declare module.exports: $Exports<'planck-js/lib/joint/WeldJoint'>;
}
declare module 'planck-js/lib/joint/WheelJoint.js' {
  declare module.exports: $Exports<'planck-js/lib/joint/WheelJoint'>;
}
declare module 'planck-js/lib/license.js' {
  declare module.exports: $Exports<'planck-js/lib/license'>;
}
declare module 'planck-js/lib/Manifold.js' {
  declare module.exports: $Exports<'planck-js/lib/Manifold'>;
}
declare module 'planck-js/lib/Rope.js' {
  declare module.exports: $Exports<'planck-js/lib/Rope'>;
}
declare module 'planck-js/lib/Settings.js' {
  declare module.exports: $Exports<'planck-js/lib/Settings'>;
}
declare module 'planck-js/lib/Shape.js' {
  declare module.exports: $Exports<'planck-js/lib/Shape'>;
}
declare module 'planck-js/lib/shape/BoxShape.js' {
  declare module.exports: $Exports<'planck-js/lib/shape/BoxShape'>;
}
declare module 'planck-js/lib/shape/ChainShape.js' {
  declare module.exports: $Exports<'planck-js/lib/shape/ChainShape'>;
}
declare module 'planck-js/lib/shape/CircleShape.js' {
  declare module.exports: $Exports<'planck-js/lib/shape/CircleShape'>;
}
declare module 'planck-js/lib/shape/CollideCircle.js' {
  declare module.exports: $Exports<'planck-js/lib/shape/CollideCircle'>;
}
declare module 'planck-js/lib/shape/CollideCirclePolygone.js' {
  declare module.exports: $Exports<'planck-js/lib/shape/CollideCirclePolygone'>;
}
declare module 'planck-js/lib/shape/CollideEdgeCircle.js' {
  declare module.exports: $Exports<'planck-js/lib/shape/CollideEdgeCircle'>;
}
declare module 'planck-js/lib/shape/CollideEdgePolygon.js' {
  declare module.exports: $Exports<'planck-js/lib/shape/CollideEdgePolygon'>;
}
declare module 'planck-js/lib/shape/CollidePolygon.js' {
  declare module.exports: $Exports<'planck-js/lib/shape/CollidePolygon'>;
}
declare module 'planck-js/lib/shape/EdgeShape.js' {
  declare module.exports: $Exports<'planck-js/lib/shape/EdgeShape'>;
}
declare module 'planck-js/lib/shape/PolygonShape.js' {
  declare module.exports: $Exports<'planck-js/lib/shape/PolygonShape'>;
}
declare module 'planck-js/lib/Solver.js' {
  declare module.exports: $Exports<'planck-js/lib/Solver'>;
}
declare module 'planck-js/lib/util/common.js' {
  declare module.exports: $Exports<'planck-js/lib/util/common'>;
}
declare module 'planck-js/lib/util/create.js' {
  declare module.exports: $Exports<'planck-js/lib/util/create'>;
}
declare module 'planck-js/lib/util/options.js' {
  declare module.exports: $Exports<'planck-js/lib/util/options'>;
}
declare module 'planck-js/lib/util/Pool.js' {
  declare module.exports: $Exports<'planck-js/lib/util/Pool'>;
}
declare module 'planck-js/lib/util/Timer.js' {
  declare module.exports: $Exports<'planck-js/lib/util/Timer'>;
}
declare module 'planck-js/lib/World.js' {
  declare module.exports: $Exports<'planck-js/lib/World'>;
}
declare module 'planck-js/test/BasicTest.js' {
  declare module.exports: $Exports<'planck-js/test/BasicTest'>;
}
declare module 'planck-js/test/CCDTest.js' {
  declare module.exports: $Exports<'planck-js/test/CCDTest'>;
}
declare module 'planck-js/test/CollisionTest.js' {
  declare module.exports: $Exports<'planck-js/test/CollisionTest'>;
}
declare module 'planck-js/test/MathTest.js' {
  declare module.exports: $Exports<'planck-js/test/MathTest'>;
}
declare module 'planck-js/test/PoolTest.js' {
  declare module.exports: $Exports<'planck-js/test/PoolTest'>;
}
declare module 'planck-js/test/testutil/expect.js' {
  declare module.exports: $Exports<'planck-js/test/testutil/expect'>;
}
declare module 'planck-js/test/testutil/memo.js' {
  declare module.exports: $Exports<'planck-js/test/testutil/memo'>;
}
declare module 'planck-js/testbed/client.js' {
  declare module.exports: $Exports<'planck-js/testbed/client'>;
}
declare module 'planck-js/testbed/index.js' {
  declare module.exports: $Exports<'planck-js/testbed/index'>;
}
declare module 'planck-js/testbed/server.js' {
  declare module.exports: $Exports<'planck-js/testbed/server'>;
}
